library('private-pipeline-library')
library('jenkins-shared')

def settings =[
    useMvnw: true,
    javaVersion : 'OpenJDK 17',
    runTests: true,
    performSonarAnalysis: false,
    runFeatureBranchPolicyEvaluations: true,
    onSuccess: { build, env ->
      notifyChat(env: env, currentBuild: build, room: 'nxrm-notifications')
    },
    onFailure: { build, env ->
      notifyChat(env: env, currentBuild: build, room: 'nxrm-notifications')
    },
    iqPolicyEvaluation: { stage ->
      nexusPolicyEvaluation iqStage: stage, iqApplication: 'nxrm3-maven-plugin',
        iqScanPatterns: [[scanPattern: '**/target/*.jar']],
        iqModuleExcludes: [[moduleExclude: 'testsuite/**']]
    }
]

mavenSnapshotPipeline(settings)